POST http://localhost:3000/auth/register
Content-Type: application/json

{
  "email": "john.doe@example.com",
  "password": "joe90joe"
}

###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email":"kclov@gmail.com",
    "password":"rebase90"
}

###

POST http://localhost:3000/auth/login
Content-Type: application/json

{
   "email": "kbrand@gmail.com",
   "password": "joe90joe"
}