import {Router} from 'express'
import createError from 'http-errors'
import * as users from '../models/users.js'
import { parse } from '../lib/validate.js'
import { userSchema } from '../lib/schemas.js'
import { hashPassword, verifyPassword } from '../lib/password.js'